server:
  port: 8081

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: false
    locations: classpath:db/migration

logging:
  level:
    root: WARN  # Default log level for the entire application
    org.springframework.web: DEBUG  # More detailed logs for Spring Web
  pattern:
    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss}) %([%thread]) %highlight(%-5level) %(%logger{36}) - %msg%n"  # Console log format